version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run:
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: npm test -- --ci --maxWorkers=2
      - run: npx codecov
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  test:
    jobs:
      - test
